# Problem Set 3: Solutions

Due **10 Feb 2021**

Note that there's usually more than one way to achive the same result. As such, these answers show just one (or two) possibilities. You can have a perfectly valid code which achieves the same but differs from below.

In [1]:
from IPython.core.interactiveshell import InteractiveShell  # This is to display all outputs in a cell
InteractiveShell.ast_node_interactivity = "all"             # not just the last one (can also be set in preferences)

### 1. Import the numpy package under the name `np` 
(**hint**: import … as …)

In [4]:
import numpy as np

### 2. Basics of array creation

Create an array:
 - of 10 zeros
 - of 10 zeros except the fifth entry is a 1
 - with values ranging from 7 to 28
 - with values ranging from 7 to 28, but only even numbers
 - with values ranging from 7 to 28, but in reverse order
 - of size 10 with values ranging from 0 to 1, evenly spaced, with both endpoints excluded
 - of size 50, with random integers between 0 and 10
     - use `bincount` and `argmax` to find the most frequently occurring value
 
 
 
**Hint**: You can use the indexing method `start:stop:step` (not specific to NumPy): it's a general slicing which says include elements from `start` (inclusive) to `stop` (not including) taking every `step` element. If `start` is omitted, this means start from the beginning; if `stop` is omitted, this means continue till the end of the sequence. Finally, negative step means count from the end. So, `::2` takes every other element `::3` every third, etc. Negative indexes read from the end forwards, so `::-1` reads in plain language: "take the whole sequence and read from the end using step 1."

In [205]:
#i)
a=np.zeros(10)
print("i:\n",a)
#ii)
b=np.zeros(10)
b[4]=1
print("ii:\n",b)
#iii)
c=np.arange(7,28) 
print("iii:\n",c)
#iv)
d=np.arange(7,28) 
d= d[d%2==0]
print("iv:\n",d)
#v)
e=np.arange(7,28)
e=np.flip(e)
print("v:\n",e)
#vi)
f=np.linspace(0,1,11, endpoint=False)[1:]
print("vi:\n",f)
#vii)
g=np.random.randint(0, 10, 50)
print("vii:\n",g)
print("\n",np.bincount(g))
print("\n",np.bincount(g).argmax())

i:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ii:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
iii:
 [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
iv:
 [ 8 10 12 14 16 18 20 22 24 26]
v:
 [27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7]
vi:
 [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
vii:
 [9 4 8 7 4 3 8 9 2 1 3 0 8 7 8 0 7 1 8 7 8 6 2 6 6 4 3 8 5 6 8 9 8 9 4 9 0
 0 4 7 6 1 9 2 3 2 3 6 9 5]

 [4 3 4 5 5 2 6 5 9 7]

 8


### 3.  Multi-Dimensional Arrays

Create a:
 - 5x5 matrix with values from 0 to 24
 - 5x5 matrix with random values between 0 and 1
     - find the min and max values
     - find the mean
     - find the mean of each row (store this as a vertical vector (a (5x1 matrix)) **Hint**: keepdims=True

In [212]:
#i)
arr=np.arange(25).reshape((5,5))   
print("5x5 matrix with values from 0 to 24: \n", arr)

#ii)
arr=np.random.random((5,5))
print("5x5 matrix with random values between 0 and 1: \n", arr)
print("Minimum Value: \n", np.min(arr))
print("Maximum Value: \n", np.max(arr))
print("Mean: \n", np.mean(arr))
arr_rmean=(arr.mean(axis=1).reshape(5,1))
print("Mean of each row as a 5x1 vector: \n", arr_rmean)

5x5 matrix with values from 0 to 24: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
5x5 matrix with random values between 0 and 1: 
 [[0.01224607 0.62583154 0.62558549 0.9505414  0.55958378]
 [0.05298752 0.91009194 0.5559045  0.67229247 0.96760145]
 [0.29344276 0.42479848 0.28480968 0.73269371 0.93435496]
 [0.92276601 0.72271465 0.65057097 0.41407666 0.13352559]
 [0.56798334 0.5060703  0.14861409 0.31446722 0.44449638]]
Minimum Value: 
 0.012246067567005747
Maximum Value: 
 0.9676014453849894
Mean: 
 0.5371220370546748
Mean of each row as a 5x1 vector: 
 [[0.55475765]
 [0.63177558]
 [0.53401992]
 [0.56873077]
 [0.39632627]]


### 4. How to find the closest value (to a given scalar) in a vector?
Write a function that takes an array and find the index (and the associated value) of the value closest to the mean.
Test on `x = np.random.random(12)`.

In [216]:
def closest_to_mean(arr):
    """
    input: arr, an np array of numeric types
    output: the index closed to the mean of the array
    """
    arr_mean=float(np.mean(arr)) #Calculates mean of the array as a float 
    abs_arr=np.abs(arr-arr_mean) #Generates absoulte array of deviaations between original array and array mean
    closest_index=abs_arr.argmin() #Finds the index of the minimum deviation 
    closest_val=arr[abs_arr.argmin()] #Finds the array value closest using the minimum deviation index 
    print(" Input Array: \n", arr ,"\n","Array Mean: \n", arr_mean)
    print(" Output Index : Output Value \n", closest_index, ":", closest_val)
    return 

x = np.random.random(12)
closest_to_mean(x)

 Input Array: 
 [0.0636511  0.17400446 0.53760104 0.04379888 0.65725983 0.2965003
 0.93789928 0.14503819 0.41315419 0.4695772  0.45287443 0.40734604] 
 Array Mean: 
 0.38322541236897556
 Output Index : Output Value 
 11 : 0.40734604496900517


### 5. Boolean Indexing

Create a function `odd_v_even` which: 
 - Takes as input a 5x5 matrix and creates a new matrix, `x`, that is the same as the input matrix except with all even numbers negated. You can use either.
     -  Boolean Masking/Indexing
     -  `np.where(cond, if-arr, else-arr)`
 - The function should return the matrix `x` as well as how many rows of `x` have a sum greater than 0. **Hint**: To calculate how many rows have a sum >0, you can calculate sums across each row of `x`, then can use boolean indexing to get True and False values, then use sum to add Trues (1) and Falses (0).
 
Finally, create a 5x5 matrix, called `z`, of random integers between 0 and 10. Run this function on `z`.

In [1]:
def odd_v_even(z):
    """
    input: z is a 5x5 matrix (np object)
    output: (x, a) where x is a matrix with even values of z negated and a an int, the number of rows with sum >0
    """
    x=np.where(z%2==0, -z, z) #Creates X, a negative copy of array Z if elements are even. 
    xrow_sum=x.sum(axis=1) #Creates a new array consisting of the summation of each row of x
    a_count=0 #Helper variable 
    for i in range(len(x)): #Iterates i within a range of x's length 
        if xrow_sum[i]>0: #Tests if the ith element of xrow_sum (summation of ith row of x) is positive
            a_count +=1 #Increases counter if true
    print("x: \n", x)
    print("a:", a_count)
    return 

z=np.random.randint(10, size=(5,5)) #Generates input array which satisfies the requirements of z
odd_v_even(z)

NameError: name 'np' is not defined

In [10]:
def odd_v_even(z):
    x=np.where(z//2==0, -z, z) 
    x_sum=x.sum(axis=1) 
    a=0  
    for i in range(5):
        if x_sum[i]>0: 
            a +=1 
    print(x)
    print(a)
    return 

z=np.random.randint(10, size=(5,5)) #Generates input array which satisfies the requirements of z
odd_v_even(z)

[[ 6  2  4  3  9]
 [ 4  3 -1  4  2]
 [ 0  7  3  8  2]
 [ 6  9  9  7  4]
 [ 3  2  9  9  6]]
5
